version: 1.0.{build}
image: Visual Studio 2015


platform:
    #- Any CPU
    - x86
    - x64

configuration:
    - Debug
    - Release

install:
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"

build:
    parallel: true                  # enable MSBuild parallel builds
    verbosity: minimal

build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - msbuild MusicPlayer.sln /m /p:configuration="%configuration%" /p:platform="%platform%"

after_build:
    - cd "%APPVEYOR_BUILD_FOLDER%"\MusicPlayer
    - ps: >-

        if ($env:PLATFORM -eq "x64") {
            Push-AppveyorArtifact "bin\$($env:PLATFORM)\$($env:CONFIGURATION)\MusicPlayer.dll" -FileName MusicPlayer.dll
        }

        if ($env:PLATFORM -eq "x86" ) {
            Push-AppveyorArtifact "bin\$($env:PLATFORM)\$($env:CONFIGURATION)\MusicPlayer.dll" -FileName MusicPlayer.dll
        }

        if ($($env:APPVEYOR_REPO_TAG) -eq "true" -and $env:CONFIGURATION -eq "Release") {
            if($env:PLATFORM -eq "x64"){
            $ZipFileName = "MusicPlayer_$($env:APPVEYOR_REPO_TAG_NAME)_x64.zip"
            7z a $ZipFileName bin\$env:CONFIGURATION\MusicPlayer.dll
            }
            if($env:PLATFORM -eq "x86"){
            $ZipFileName = "MusicPlayer_$($env:APPVEYOR_REPO_TAG_NAME)_x86.zip"
            7z a $ZipFileName bin\$env:PLATFORM\$env:CONFIGURATION\MusicPlayer.dll
            }
        }

artifacts:
  - path: MusicPlayer_*.zip
    name: releases

deploy:
    provider: GitHub
    auth_token:
        secure: !!TODO, see https://www.appveyor.com/docs/deployment/github/#provider-settings!!
    artifact: releases
    draft: false
    prerelease: false
    force_update: true
    on:
        appveyor_repo_tag: true
        configuration: Release
